name: WISE Team
title: WISE Manual
email: 
description: A comprehensive user manual to WISE vote delegation system
url: ""
baseurl: "/"
logo_link: "/"
manual_link: "/introduction"
github_username:  wise-team
repository: "wise-team/steem-wise-manual"

title_separator: "|"
site.locale: pl-PL
search: false


# Build settings
markdown: kramdown
plugins:
  - jekyll-redirect-from
theme: minimal-mistakes-jekyll
include: [ "_pages" ]

## Front matter defaults
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: single
      sidebar:
        nav: "menu"
      urls:
        #ยง 'votingPage: ' + data.config.votingPage.url.production
        votingPage: https://wise.vote/voting-page/
        

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock


# Prayer:
#  Gloria Patri, et Filio, et Spiritui Sancto, sicut erat in principio et nunc et semper et in saecula
#  saeculorum. Amen. In te, Domine, speravi: non confundar in aeternum.
