name: WISE Team
title: Steem WISE Manual
email: 
description: A comprehensive user manual to Steem WISE vote delegation system
url: "https://noisy-witness.github.io"
baseurl: "/steem-wise-manual"
logo_link: "/steem-wise-manual"
manual_link: "/steem-wise-manual/introduction"
github_username:  noisy-witness
repository: "noisy-witness/steem-wise-manual"

title_separator: "|"
site.locale: pl-PL
search: false


# Build settings
markdown: kramdown
plugins:
  # no plugins
remote_theme: "mmistakes/minimal-mistakes"
include: [ "_pages" ]

## Front matter defaults
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: single
      sidebar:
        nav: "menu"
        

exclude:
  - Gemfile
  - Gemfile.lock


# Prayer:
#  Gloria Patri, et Filio, et Spiritui Sancto, sicut erat in principio et nunc et semper et in saecula
#  saeculorum. Amen. In te, Domine, speravi: non confundar in aeternum.