name: WISE Team
title: Steem WISE Handbook
email: 
description: >-
  A comprehensive user manual to Steem WISE vote delegation system
baseurl: "/steem-wise-handbook"
url: "http://noisy-witness.github.io/steem-wise-handbook" 
github_username:  noisy-witness
repository: "noisy-witness/steem-wise-handbook"

title_separator: "|"
site.locale: pl-PL
search: false


# Build settings
markdown: kramdown
plugins:
  # no plugins
remote_theme: "mmistakes/minimal-mistakes"

## Front matter defaults
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: single
      sidebar:
        nav: "menu"
        

exclude:
  - Gemfile
  - Gemfile.lock