version: "3"

networks:
  proxy-tier:
    external:
      name: caddy-proxy

services:
  #ยง data.config.manual.docker.services.frontend.name + ':'
  frontend:
    expose:
      #ยง '- ' + data.config.manual.docker.services.frontend.port
      - 4000
    networks:
      - proxy-tier
    restart: always
