version: "3"

networks:
  proxy-tier:
    external:
      name: caddy-proxy

services:
  #ยง data.config.manual.docker.services.frontend.name + ':'
  frontend:
    networks:
      - proxy-tier
    restart: always
