version: "3"

services: 
  #ยง data.config.manual.docker.services.frontend.name + ':'
  frontend:
    #ยง 'container_name: ' + data.config.manual.docker.services.frontend.container
    container_name: wise-manual
    #ยง 'image: ' + data.config.manual.docker.services.frontend.image
    image: wise/manual
    build: .
    ports:
      - 4000:4000
    restart: always
