version: "3"

services:
  wise-manual:
    container_name: wise-manual
    image: jekyll/builder:3.7
    command: jekyll serve
    volumes:
      - $PWD:/srv/jekyll
    ports:
      - 4000:4000
    environment:
      NODE_ENV: production
