version: "3"

networks:
  proxy-tier:
    external:
      name: caddy-proxy

services:
  wise-manual:
    container_name: wise-manual
    build: .
    ports:
      - 4000:4000
    networks:
      - proxy-tier
    environment:
      NODE_ENV: production
